app:
  title: Backstage App by Spotify (Development)

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    github:
      development:
        clientId: ffaeda67b29f27cead6a
        clientSecret: bd226d696e2453d992e1488d6eb52bda7178213f