app:
  title: Backstage App by Spotify (Development)

integrations:
  # GitHub App Token to Auth
  github:
    - host: github.com
      token: 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

scaffolder:
  # Override defaults
  defaultAuthor:
    name: Scaffolder
    email: scaffolder@backstage.io
  defaultCommitMessage: 'Initial commit'

catalog:
  rules:
    - allow: [Component, Group, User, Resource, Location, Template, Domain, System]